### ISSUE TITLE
[bug report] There are some problem in python environment install step

### ISSUE THREAD

**Issue by Yangxiamao** [949867756/AutoAttendYuKeTang#8]
My computer system is MacOS monterey 12.2.1. When I followed the install step, in "pip install -r requirements" go wrong. 
This step should be "pip install -r requirements.txt".
<img width="1403" alt="Screen Shot 2022-04-04 at 10 39 21 AM" src="https://user-images.githubusercontent.com/47442074/161465894-d5a0ef2f-de42-430c-bb00-573ed7738617.png">

**Comment by VidocqH** [comment]
Thanks
